{% set name = "napari-mouse-controls" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-mouse-controls-{{ version }}.tar.gz
  sha256: 0dd9ee41146a3cb73ff8cf9378e242331d2ea9b0c4088188b4bce1650a45c7e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - napari
    - napari-plugin-engine >=0.1.4
    - napari-tools-menu
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - napari_mouse_controls
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/haesleinhuepf/napari-mouse-controls
  summary: Control zoom, slicing and contrast windowing with mouse and touch screen in napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
